/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Manufacturer;

import ui.InsuranceAdminRole.*;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import ui.AdministrativeRole.AdminWorkAreaJPanel;
import ui.AdministrativeRole.ManageEmployeeJPanel;
import ui.HospitalAdminRole.*;

/**
 *
 * @author jessi
 */
public class ManufacturerAdminJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Organization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Network network;
    private EcoSystem system;
    /**
     * Creates new form HospitalAdminJPanel
     */
    public ManufacturerAdminJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, Network network, EcoSystem system) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.network = network;
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageVisit = new javax.swing.JButton();
        btnManageInsurances = new javax.swing.JButton();

        setBackground(new java.awt.Color(241, 235, 218));

        btnManageVisit.setText("Manage Visit Requests");
        btnManageVisit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageVisitActionPerformed(evt);
            }
        });

        btnManageInsurances.setText("Manage Insurances");
        btnManageInsurances.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageInsurancesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnManageVisit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageInsurances, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(236, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(btnManageVisit)
                .addGap(32, 32, 32)
                .addComponent(btnManageInsurances)
                .addContainerGap(311, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageVisitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageVisitActionPerformed
        AdminManufacturerReqJPanel insvis = new AdminManufacturerReqJPanel(userProcessContainer, userAccount, organization, enterprise, network, system);
        userProcessContainer.add("insvis", insvis);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageVisitActionPerformed

    private void btnManageInsurancesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageInsurancesActionPerformed
        AdminManufacturerDrugsJPanel insins = new AdminManufacturerDrugsJPanel(userProcessContainer, userAccount,  enterprise, network, system);
        userProcessContainer.add("insins", insins);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageInsurancesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageInsurances;
    private javax.swing.JButton btnManageVisit;
    // End of variables declaration//GEN-END:variables
}
