/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.DoctorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.InsuranceRequest;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.VisitQueue;
import Business.WorkQueue.VisitRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class DoctorInsuranceJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Organization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Network network;
    private EcoSystem system;
    private ArrayList<InsuranceRequest> curriq;
    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public DoctorInsuranceJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, Network network, EcoSystem system) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.network = network;
        this.system = system;
        valueLabel.setText(enterprise.getName());
        populateRequestTable();
    }
    
    public void populateRequestTable(){
        DefaultTableModel model = (DefaultTableModel) tblVisitRequests.getModel();
        model.setRowCount(0);
        ArrayList<InsuranceRequest> iq = system.getInsuranceQueue().getInsuranceQueue();
        String doc = userAccount.getUsername();
        curriq = new ArrayList<>();
        for (InsuranceRequest req : iq) {
            if (req.getDoctor().getUsername().equals(doc)) {
                Object[] row = new Object[5];
                row[0] = req.getRequestId();
                row[1] = req.getStatus();
                row[2] = req.getDoctorComment();
                row[3] = req.getInsuranceComment();
                row[4] = req.getTestResult();
                model.addRow(row);
                curriq.add(req);
            }
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblVisitRequests = new javax.swing.JTable();
        btnReqTest = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        txtProblem = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        lblResults = new javax.swing.JLabel();
        lblProblem = new javax.swing.JLabel();
        btnApprove = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(241, 235, 218));
        setLayout(null);

        tblVisitRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Message", "Receiver", "Status", "Result"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblVisitRequests);
        if (tblVisitRequests.getColumnModel().getColumnCount() > 0) {
            tblVisitRequests.getColumnModel().getColumn(0).setResizable(false);
            tblVisitRequests.getColumnModel().getColumn(1).setResizable(false);
            tblVisitRequests.getColumnModel().getColumn(2).setResizable(false);
            tblVisitRequests.getColumnModel().getColumn(3).setResizable(false);
        }

        add(jScrollPane1);
        jScrollPane1.setBounds(99, 116, 456, 97);

        btnReqTest.setBackground(new java.awt.Color(0, 153, 255));
        btnReqTest.setText("Request Test");
        btnReqTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReqTestActionPerformed(evt);
            }
        });
        add(btnReqTest);
        btnReqTest.setBounds(222, 75, 125, 29);

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel);
        enterpriseLabel.setBounds(21, 27, 127, 30);

        valueLabel.setText("<value>");
        add(valueLabel);
        valueLabel.setBounds(178, 27, 158, 26);

        txtProblem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProblemActionPerformed(evt);
            }
        });
        add(txtProblem);
        txtProblem.setBounds(188, 244, 116, 26);
        add(jTextField2);
        jTextField2.setBounds(449, 244, 106, 26);

        lblResults.setText("LabResults :");
        add(lblResults);
        lblResults.setBounds(345, 249, 76, 16);

        lblProblem.setText("Comment");
        add(lblProblem);
        lblProblem.setBounds(99, 254, 61, 16);

        btnApprove.setBackground(new java.awt.Color(0, 153, 255));
        btnApprove.setText("Approve");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });
        add(btnApprove);
        btnApprove.setBounds(257, 306, 96, 29);

        btnReject.setBackground(new java.awt.Color(255, 102, 102));
        btnReject.setText("Reject");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });
        add(btnReject);
        btnReject.setBounds(428, 306, 82, 29);

        jButton1.setBackground(new java.awt.Color(0, 153, 255));
        jButton1.setText("View");
        add(jButton1);
        jButton1.setBounds(431, 75, 75, 29);

        jButton2.setBackground(new java.awt.Color(0, 153, 255));
        jButton2.setText("Save");
        add(jButton2);
        jButton2.setBounds(99, 306, 75, 29);

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(61, 73, 97, 29);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/saline.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1800, 900);
    }// </editor-fold>//GEN-END:initComponents

    private void btnReqTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReqTestActionPerformed
        int selectedRowIndex = tblVisitRequests.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Request not selected");
            return;
        }
        InsuranceRequest ir = curriq.get(selectedRowIndex);
        ir.setStatus("Lab Test Requested");
        populateRequestTable();
    }//GEN-LAST:event_btnReqTestActionPerformed

    private void txtProblemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProblemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProblemActionPerformed

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        int selectedRowIndex = tblVisitRequests.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Request not selected");
            return;
        }
        InsuranceRequest ir = curriq.get(selectedRowIndex);
        ir.setDoctorComment(txtProblem.getText());
        ir.setStatus("Doctor Approved");
        populateRequestTable();
    }//GEN-LAST:event_btnApproveActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        int selectedRowIndex = tblVisitRequests.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Request not selected");
            return;
        }
        InsuranceRequest ir = curriq.get(selectedRowIndex);
        ir.setDoctorComment(txtProblem.getText());
        ir.setStatus("Docotor Rejected");
        populateRequestTable();
    }//GEN-LAST:event_btnRejectActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReject;
    private javax.swing.JButton btnReqTest;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblProblem;
    private javax.swing.JLabel lblResults;
    private javax.swing.JTable tblVisitRequests;
    private javax.swing.JTextField txtProblem;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
